[DROOLS-7253] Review and improve drools-lsp parser Visitor design
mariofusco/drools-lsp pull request #16
Opened 2022-12-12 07:24 UTC by tkobayas

- Remove currentConstructStack. Utilize return object instead.

2022-12-12 07:27 UTC, tkobayas commented
Removed `currentConstructStack`. Instead, utilize return objects of Visitor methods, so it's more natural to AST traversing.

2022-12-12 08:31 UTC, gitgabrio requested changes
HI @tkobayas 
Thanks for the PR: IMO it is better, but still I would avoid those three instance variables `packageDescr,` `currentRule` and `currentPattern`: as far as I see they are strictly related to the status of different "contexts", so, if possible, I think it would be better to embed them in the appropriate context, and altogether avoid to rely upon such "spurious" variables: wdyt ?

2022-12-12 08:31 UTC, gitgabrio commented on drools-parser/src/main/java/org/drools/parser/DRLVisitorImpl.java
>              currentPattern.setSource(from);
Hi @tkobayas !
I'm not sure to follow the logic of `currentPattern.setSource(from);` (@187) and `currentPattern = null;` (@190) and, in general, of this method: at line @101 `currentPattern` points to same object as `patternDescr`; in the `if` statement the status of that object is changed (through `currentPattern`), and then `currentPattern`reference is nullified: I have the impression that that `currentPattern` is not needed here and, in general, being it a "status" of the class, make the code slightly harder to understand/maintain then needed: wdyt ?

2022-12-16 06:05 UTC, tkobayas commented
Removed `packageDescr`, `currentRule` and `currentPattern`. Now Descrs are constructed by return objects along with Visitor AST travseral. Could you share any thoughts on this? @gitgabrio @mariofusco

2022-12-16 08:03 UTC, gitgabrio approved these changes
Hi @tkobayas 
Thanks, you really imrpoved that! You get rid of all those hidden side effects and also proveded a better typing of returned object: LGTM!

2022-12-16 08:48 UTC, mariofusco approved these changes

2022-12-16 08:48 UTC, merged